---

resource_types:
- name: maven-resource
  type: docker-image
  source:
    repository: pivotalpa/maven-resource
    tag: latest

resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/MarcialRosales/app1
    branch: master

- name: artifact-repo
  type: maven-resource
  source:
    url: http://192.168.1.36:8081/nexus/content/repositories/snapshots
    artifact: com.example:demo:jar
    username: admin
    password: admin123

jobs:
- name: build-and-verify
  plan:
  - get: source-code
    trigger: true
  - task: build-and-verify
    file: source-code/tasks/build.yml
  - put: artifact-repo
    params:
      file: build-artifact/*.jar
      pom_file: source-code/pom.xml

- name: deploy
  plan:
  - get: artifact-repo
    trigger: true
    passed: [build-and-verify]
  - get: source-code
  - task: generate-manifest
    file: source-code/tasks/generate-manifest.yml
    params:
      APP_NAME: demo
      APP_HOST: demo
      APP_DOMAIN: mydomain
  - task: check
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: busybox
      inputs:
        - name: manifest
      outputs:
        - name: greetings
      run:
        path: sh
        args:
          - -c
          - |
            ls manifest
            cat manifest/manifest.yml
